config/routes.rb
Rails.application.routes.draw do
  root to:'welcome#index'
  
  
  get "adhesion", to:'bememberships#new'
  get 'good', to:"bememberships#page_good"
  
  
  #Legal
  get "charte", to:"legals#show"
  get "vie-privée", to:"privates#show"
  
  
  get "agir", to:'agir#index'
  
  get "action-projet", to:'action_page#index'
  #get "dons", to:'donner#index'
  #### Accounted #####
  get "connecting", to:'accounted#signInMember'
  get "adhesion-partner", to:'accounted#signUpMember'
  get "admin-accounted", to:'accounted#signUpAdmin'
  
  #DASHBOARD
  get "dashboard", to:'dashboard#index'
  get "parametres", to:'dashboard#home'
  get "agisons-ensemble", to:"involved#index"
  
  # MEMBERSHIP
  get "adherer", to:'membership#index'
  get "members-list", to:"membership#memberslist"
  get "beaction-v", to:"membership#beaction"


  # CAMPAGNES
  get "new-campagne", to:"campagnes#new"
  get "campagnes", to:"campagnes#index"
  get "edit-campagnes", to:"campagnes#edit"

  #BENEVOLS
  get "New-benevol", to:"benevols#new"
  get "benevols", to:"benevols#index"

  #PROJETS
  get "new-projet", to:"projets#new"
  get "projets-list", to:"projets#index"
  #put "edit-projet", to:"projets#edit"
  


  devise_scope :user do
    get 'profile/edit'    => 'devise/registrations#edit',   :as => :edit_user_registration
    get 'profile/cancel'  => 'devise/registrations#cancel', :as => :cancel_user_registration
    
  end
  

  resources :bememberships
  resources :privates
  resources :legals
  resources :articles
  resources :blogs
  resources :benevols, except: %i[new, index]
  resources :projets
  resources :campagnes
  
  devise_for  :users,
    :path => '',
    :path_names =>
      { :sign_in => 'beaction',
        :sign_out => 'logout',
        :sign_up =>   '', 
          :registration => 'signup-admin',
          :edit => 'edit'
      }
  
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  has_one_attached :heroImg
  

  STATUS= ["Encours", "Approbation", "Public", "La lune", "Archive"]
  validates :title, :content, :write_date, :slug, presence: true
  validates :title, :content, length: { minimum:5}


   ################## SLUG ###############
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
   title_changed?
  end
end

app/models/bemembership.rb
class Bemembership < ApplicationRecord
    validates :first_name, :last_name, :email,
              :country, :contact, :gender, :terms, :citytown,
                :employer, :profession, :matrimonial,
                 :nationality, presence: true

    
    validates :first_name, :last_name, :source,
                :employer, :profession, :matrimonial,
                :nationality,
              format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ },
              length: { maximum: 30,
              message: "%{value} verifier votre nom complet"}
    validates :contact,
             #format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ },
              length: { maximum: 16,
              message: "%{value} verifier votre Numéro"}
end

app/models/benevol.rb
class Benevol < ApplicationRecord
     has_one_attached :img
    STATUS= ["La Lune", "Status 2", "Status 3"]
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user

   ################## SLUG ###############
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
   title_changed?
  end

  
end

app/models/campagne.rb
class Campagne < ApplicationRecord
  belongs_to :user
  has_one_attached :heroImg
  has_rich_text :content
  
  Campagne.all.with_rich_text_content # Preload the body without attachments.
  Campagne.all.with_rich_text_content_and_embeds # Preload both body and attachments.


  STATUS= ["Encours", "Approver", "La lune", "Archive" ]
  validates :title, :content, :start_date, :amount, presence: true
  #validates_comparison_of :start_date, greater_than: -> { Date.today }
  validates :title, :content, length: { minimum:5}


  ################## SLUG ###############
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
   title_changed?
  end
end

app/models/legal.rb
class Legal < ApplicationRecord
  belongs_to :user
end

app/models/membership.rb
class Membership < ApplicationRecord
    
end

app/models/private.rb
class Private < ApplicationRecord
  belongs_to :user
end

app/models/projet.rb
class Projet < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  #Projet.all.with_rich_text_content # Preload the body without attachments.
  #Projet.all.with_rich_text_content_and_embeds # Preload both body and attachments.
  has_one_attached :heroImg

  STATUS= ["Encours", "Approver", "La lune", "Archive"]
  validates :title, :content, :start_date, :amount, presence: true
  validates :title, :content, length: { minimum:5}


  ################## SLUG ###############
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
   title_changed?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :posts
  has_many :abouts
  has_many :projets
  has_many :campagnes
  has_many :blogs
  has_many :articles
  has_many :legals
  has_many :privates
  has_one_attached :avatar

  def full_name
    self.full_name = "#{self.first_name} #{self.last_name}" 
  end  
   
  def slug
    self.slug = "#{self.full_name}" 
  end

  validates :first_name, :last_name, :full_name, :email, :password,
              :country, :full_contact, presence: true
    
   validates :full_name,presence: true,
              format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ },
              length: { minimum:5, maximum: 30,
              message: "%{value} verifier votre nom complet"}

                

   ################## SLUG ###############
  extend FriendlyId
  friendly_id :full_name, use: :slugged
  
  def should_generate_new_friendly_id?
    full_name_changed?
  end 
 
  
  ################## BEFORE SAVE  #########
  before_save do
    #self.country            = country.strip.squeeze(" ")
    self.full_contact            = full_contact .strip.squeeze(" ")
    self.first_name         = first_name.strip.squeeze(" ").downcase.capitalize
    self.last_name          = last_name.strip.squeeze(" ").downcase.capitalize
  end
end

app/controllers/action_page_controller.rb
class ActionPageController < ApplicationController
  def index
    @ActionProjets = Projet.all.order('created_at desc')
  end
end

app/helpers/action_page_helper.rb
module ActionPageHelper
end

app/helpers/agir_helper.rb
module AgirHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/benevols_helper.rb
module BenevolsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/involved_helper.rb
module InvolvedHelper
end

app/helpers/legals_helper.rb
module LegalsHelper
end

app/helpers/privates_helper.rb
module PrivatesHelper
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/action_page/index.html.erb
<%= render "welcome/shared/header" %>
<!-- ====== Banner Section Start -->
    <div
      class="
        relative
        z-10
        pt-[120px]
        md:pt-[130px]
        lg:pt-[160px]
        pb-[100px]
        bg-gray-200
        overflow-hidden
      "
    >
      <div class="container">
        <div class="flex flex-wrap items-center -mx-4">
          <div class="w-full px-4">
            <div class="text-center">
              <h1 class="font-semibold text-black text-4xl">Nos Projets Action <sup>+</sup></h1>
            </div>
          </div>
        </div>
      </div>
      <div>
        <span class="absolute top-0 left-0 z-[-1]">
          <svg
            width="495"
            height="470"
            viewBox="0 0 495 470"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <circle
              cx="55"
              cy="442"
              r="138"
              stroke="white"
              stroke-opacity="0.04"
              stroke-width="50"
            />
            <circle
              cx="446"
              r="39"
              stroke="white"
              stroke-opacity="0.04"
              stroke-width="20"
            />
            <path
              d="M245.406 137.609L233.985 94.9852L276.609 106.406L245.406 137.609Z"
              stroke="white"
              stroke-opacity="0.08"
              stroke-width="12"
            />
          </svg>
        </span>
        <span class="absolute top-0 right-0 z-[-1]">
          <svg
            width="493"
            height="470"
            viewBox="0 0 493 470"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <circle
              cx="462"
              cy="5"
              r="138"
              stroke="white"
              stroke-opacity="0.04"
              stroke-width="50"
            />
            <circle
              cx="49"
              cy="470"
              r="39"
              stroke="white"
              stroke-opacity="0.04"
              stroke-width="20"
            />
            <path
              d="M222.393 226.701L272.808 213.192L259.299 263.607L222.393 226.701Z"
              stroke="white"
              stroke-opacity="0.06"
              stroke-width="13"
            />
          </svg>
        </span>
      </div>
    </div>
    <!-- ====== Banner Section End -->
    
    <!-- ====== Blog Section Start -->
    <section class="pt-20 lg:pt-[120px] pb-10 lg:pb-20">
      <div class="container">
        <div class="flex flex-wrap -mx-4">
        <% @ActionProjets.each do |action| %>
          <div class="w-full md:w-1/2 lg:w-1/3 px-4">
            <div class="mb-10 group wow fadeInUp" data-wow-delay=".1s">
              <div class="rounded overflow-hidden mb-8">
                <%= link_to projet_path(action), class:"block" do %>
                  <% if  %>
                  <%= image_tag(action.heroImg, class:"w-full transition group-hover:scale-125 group-hover:rotate-6") %>
                  <% else %>
                  <%= image_tag "media/5.jpeg", alt:"image", class:"w-full transition group-hover:scale-125 group-hover:rotate-6"%>
                  <% end %>
                <% end %>
              </div>
              <div>
                <span
                  class=" bg-primary rounded inline-block text-center py-1 px-4 text-xs leading-loose font-semibold text-white mb-5">
                  <%= action.start_date %>
                </span>
                <h3>
                  <%= link_to projet_path(action), class:" font-semibold text-xl sm:text-2xl lg:text-xl xl:text-2xl mb-4 inline-block text-dark hover:text-primary" do %>
                    <%= action.title %>
                  <% end %>
                </h3>
                <p class="text-base text-body-color">
                    <%= link_to projet_path(action), class:"hover:text-black text-black no-underline" do %>
                        <%= truncate(strip_tags(action.content.to_s.html_safe), length: 200)%>
                        <span class="bg-blue-300" id=start-reading><i class="mx-2">Lire plus >> </i></span>
                    <% end %>
                </p>
              </div>
            </div>
          </div>
          
          <% end %>
          
        </div>
      </div>
    </section>
    <!-- ====== Blog Section End -->
    

    <%= render "welcome/shared/preloader" %>
    <%= render "welcome/shared/footer" %>