config/routes.rb
Rails.application.routes.draw do
  root to:'welcome#index'
  
  
  get "adhesion", to:'bememberships#new'
  get 'good', to:"bememberships#page_good"
  
  
  #Legal
  get "charte", to:"legals#show"
  get "vie-privée", to:"privates#show"
  
  
  get "agir", to:'agir#index'
  
  get "action-projet", to:'action_page#index'
  #get "dons", to:'donner#index'
  #### Accounted #####
  get "connecting", to:'accounted#signInMember'
  get "adhesion-partner", to:'accounted#signUpMember'
  get "admin-accounted", to:'accounted#signUpAdmin'
  
  #DASHBOARD
  get "dashboard", to:'dashboard#index'
  get "parametres", to:'dashboard#home'
  get "agisons-ensemble", to:"involved#index"
  
  # MEMBERSHIP
  get "adherer", to:'membership#index'
  get "members-list", to:"membership#memberslist"
  get "beaction-v", to:"membership#beaction"


  # CAMPAGNES
  get "new-campagne", to:"campagnes#new"
  get "campagnes", to:"campagnes#index"
  get "edit-campagnes", to:"campagnes#edit"

  #BENEVOLS
  get "New-benevol", to:"benevols#new"
  get "benevols", to:"benevols#index"

  #PROJETS
  get "new-projet", to:"projets#new"
  get "projets-list", to:"projets#index"
  #put "edit-projet", to:"projets#edit"
  


  devise_scope :user do
    get 'profile/edit'    => 'devise/registrations#edit',   :as => :edit_user_registration
    get 'profile/cancel'  => 'devise/registrations#cancel', :as => :cancel_user_registration
    
  end
  

  resources :bememberships
  resources :privates
  resources :legals
  resources :articles
  resources :blogs
  resources :benevols, except: %i[new, index]
  resources :projets
  resources :campagnes
  
  devise_for  :users,
    :path => '',
    :path_names =>
      { :sign_in => 'beaction',
        :sign_out => 'logout',
        :sign_up =>   '', 
          :registration => 'signup-admin',
          :edit => 'edit'
      }
  
end

app/models/bemembership.rb
class Bemembership < ApplicationRecord
    validates :first_name, :last_name, :email,
              :country, :contact, :gender, :terms, :citytown,
                :employer, :profession, :matrimonial,
                 :nationality, presence: true

    
    validates :first_name, :last_name, :source,
                :employer, :profession, :matrimonial,
                :nationality,
              format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ },
              length: { maximum: 30,
              message: "%{value} verifier votre nom complet"}
    validates :contact,
             #format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ },
              length: { maximum: 16,
              message: "%{value} verifier votre Numéro"}
end

app/controllers/bememberships_controller.rb
class BemembershipsController < ApplicationController
  before_action :set_bemembership, only: %i[ edit update destroy ]

  # GET /bememberships or /bememberships.json
  def index
    @bememberships = Bemembership.all
  end

  # GET /bememberships/1 or /bememberships/1.json
  def show
  end

  def page_good
    
  end

  # GET /bememberships/new
  def new
    @bemembership = Bemembership.new
  end

  # GET /bememberships/1/edit
  def edit
    
  end

  # POST /bememberships or /bememberships.json
  def create
    @bemembership = Bemembership.new(bemembership_params)

    respond_to do |format|
      if @bemembership.save
        format.html { redirect_to good_path, notice: "Adhésion effectuée avec succes." }
        format.json { render :show, status: :created, location: @bememberships }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bemembership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bememberships/1 or /bememberships/1.json
  def update
    respond_to do |format|
      if @bemembership.update(bemembership_params)
        format.html { redirect_to bemembership_url(@bemembership), notice: "Bemembership was successfully updated." }
        format.json { render :show, status: :ok, location: @bemembership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bemembership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bememberships/1 or /bememberships/1.json
  def destroy
    @bemembership.destroy

    respond_to do |format|
      format.html { redirect_to bememberships_url, notice: "Bemembership was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bemembership
      @bemembership = Bemembership.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bemembership_params
      params.require(:bemembership).permit(:first_name, :last_name, :email, :country,
                                            :contact, :gender, :terms, :citytown,
                                            :source, :employer, :profession, :matrimonial,
                                            :nationality)
    end
end

app/helpers/bememberships_helper.rb
module BemembershipsHelper
end

app/views/bememberships/_bemembership.html.erb
<div id="<%= dom_id bemembership %>">
  <p>
    <strong>First name:</strong>
    <%= bemembership.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= bemembership.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= bemembership.email %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= bemembership.country %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= bemembership.contact %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= bemembership.gender %>
  </p>

</div>

app/views/bememberships/_form-b.html.erb
	<% @title="Compte Admin Action+" %>

<!-- component -->
<div class="h-screen md:flex">
	<div class="relative overflow-hidden md:flex w-1/3 bg-gradient-to-tr from-green-400 to-blue-600 i justify-around items-center hidden">
		<div class="container">

			<h1 class="text-white font-bold text-4xl font-sans"> 
        <div class="before:block before:absolute before:-inset-1 before:-skew-y-3 before:bg-pink-500 relative inline-block">
          <p class="relative text-white">Adhésion a Action<sup>+</sup></p>
        </div>
      </h1>
			<p class="text-black mt-1">Vous voulez contribuer à sauver des vies ? <br> Rejoignez Action<sup>+</sup> !
<br> <span class="font-semibold underline"> C'est facile, gratuit et 1 minute suffira.</span></p>
			
    
		</div>
		<div class="absolute -bottom-32 -left-40 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
		<div class="absolute -bottom-40 -left-20 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
		<div class="absolute -top-40 -right-0 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
		<div class="absolute -top-20 -right-20 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
	</div>
	<div class="flex md:w-2/3 justify-center  items-center bg-white">
	
    <div class="flex md:w-2/3 justify-center  items-center bg-white mx-2">
    <h1 class="text-gray-800 font-bold text-2xl mb-2">Vous et Action<sup>+</sup> Agisons Ensemble pour sauver des vies</h1>
 <p class="text-sm font-normal text-gray-600 mb-2">Devenez Membre Adherent d'Action<sup>+</sup></p>

  <%= form_with(model: bemembership) do |f| %>
      <% if bemembership.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(bemembership.errors.count, "error") %> prohibited this bemembership from being saved:</h2>

          <ul>
            <% bemembership.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="flex items-center mt-8 mb-2">
        <%= f.text_field :first_name, class:"placeholder:italic placeholder:text-slate-400 outline-none border rounded-md py-2 w-full", placeholder:"Nom ..." %>
        <%= f.text_field :last_name, class:"placeholder:italic placeholder:text-slate-400 outline-none border ml-2 rounded-md py-2 w-full", placeholder:"Prénom..." %>
      </div>
	
      <%= f.email_field :email, placeholder:"Addresse Email ...", class:"placeholder:italic placeholder:text-slate-400 flex border py-2 rounded-md w-full my-2" %>			
     
      <div class="flex w-full py-2 mb-2">	
        <%= f.text_field :country, class:"pl-2 outline-none border rounded-md", placeholder:"Adresse de residence..." %>
        <%= f.text_field :contact, placeholder:"N° telephone ...", class:"flex border py-2 ml-2 rounded-md w-full placeholder:mx-4" %>	
      </div>
      <div class="flex w-full py-2">
        <div class="mr-4">
          <p class="font-semibold">Vous êtes? :</p>
        </div>
        <%= f.radio_button :gender, value:'Femme' %> <span class="mx-2">Femme</span>
        <%= f.radio_button :gender, value:'Homme' %> <span class="mx-2">Homme</span>
      </div>


      <div class="flex items-center  py-2 ">
        <%= f.check_box :terms, value:"oui", class:" mr-4", checked:true %>
        <p class="text-sm">
        
          Oui, j'adhère à <a href="#exampleModalToggle" class="font-semibold underline" > la charte des valeurs, aux statuts et 
          aux règles de fonctionnement d'Action<a><sup class="">+</sup>, ainsi qu'aux
          <a href="#exampleModalToggle2" class="font-semibold underline" >conditions générales d'utilisation <a> et à la politique
          de  <a href="#exampleModalToggle3" class="font-semibold underline" >protection des données <a> de la plateforme.
        </p>
      </div>
      <div>
        <%= f.submit "Terminer Adhésion", class:"block w-full bg-green-600 mt-2 py-2 pb-2 rounded-2xl text-white font-semibold mb-2" %>
      </div>
  <% end %>

	</div>
</div>






<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalToggleLabel">Modal 1</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Show a second modal and hide this one with the button below.
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal">Open second modal</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalToggleLabel2">Charte</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Hide this modal and show the first with the button below.
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Back to first</button>
      </div>
    </div>
  </div>
</div>


<!-- Modal 2-->
<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalToggleLabel">Modal 1</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Show a second modal and hide this one with the button below.
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal">Open second modal</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalToggleLabel2">Charte</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Hide this modal and show the first with the button below.
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Back to first</button>
      </div>
    </div>
  </div>
</div>

app/views/bememberships/_form.html.erb
<% @title="Adhésion Action+" %>

<!-- component -->
<div class="h-screen md:flex">
	<div class="relative overflow-hidden md:flex w-1/3 bg-gradient-to-tr from-green-400 to-blue-600 i justify-around items-center hidden">
		<div class="container">

			<h1 class="text-white font-bold text-4xl font-sans"> 
        <div class="before:block before:absolute before:-inset-1 before:-skew-y-3 before:bg-pink-500 relative inline-block">
          <p class="relative text-white">Adhésion a Action<sup>+</sup></p>
        </div>
      </h1>
			<p class="text-black mt-1">Vous voulez contribuer à sauver des vies ? <br> Rejoignez les Adherants d'Action<sup>+</sup> !
      <br>
      <span class="font-semibold underline"> C'est facile, gratuit et 1 minute suffira.</span></p>
			
    
		</div>
		<div class="absolute -bottom-32 -left-40 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
		<div class="absolute -bottom-40 -left-20 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
		<div class="absolute -top-40 -right-0 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
		<div class="absolute -top-20 -right-20 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
	</div>
	<div class="flex md:w-2/3 justify-center  items-center bg-white mx-2">

    <%= form_with(model: bemembership) do |f| %>
      <h1 class="text-gray-800 font-bold text-2xl ">Vous et Action<sup>+</sup> Agisons Ensemble pour sauver des vies</h1>
      <p class="text-sm font-normal text-gray-600 ">Devenez Membre Adherant d'Action<sup>+</sup></p>
        <% if bemembership.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(bemembership.errors.count, "erreur") %> trouvée. Veillez rectifier les points:</h2>

            <ul>
              <% bemembership.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="mx-2">	
        <div class="flex items-center mt-8 mb-2">
          <%= f.text_field :first_name, class:"placeholder:italic placeholder:text-slate-400
           outline-none border rounded-md py-2 w-full 
           focus:outline-none focus:ring focus:border-blue-200", 
           placeholder:"Nom ..." %>
          <%= f.text_field :last_name, class:"placeholder:italic placeholder:text-slate-400
           outline-none border ml-2 rounded-md py-2 w-full 
           focus:outline-none focus:ring focus:border-blue-200", placeholder:"Prénom..." %>
        </div>
    
        <%= f.email_field :email, placeholder:"Addresse Email ...", 
        class:"placeholder:italic placeholder:text-slate-400
           outline-none border rounded-md py-2 w-full 
           focus:outline-none focus:ring focus:border-blue-200" %>			
      
        <div class="flex items-center my-2">
          <%= f.text_field :country, class:"placeholder:italic placeholder:text-slate-400 
          border rounded-md py-2 w-full focus:outline-none focus:ring focus:border-blue-500",
           placeholder:"Pays de résidence ..." %>

          <%= f.text_field :citytown, class:"placeholder:italic placeholder:text-slate-400
           outline-none border ml-2 rounded-md py-2 w-full 
           focus:outline-none focus:ring focus:border-blue-200", 
          placeholder:"Ville de résidence ..." %>
        </div>
        
          <%= f.text_field :contact, class:"flex border py-2 rounded-md w-full
           placeholder:mx-4 focus:outline-none focus:ring focus:border-blue-500", 
           placeholder:"N° télèphone suivi de indicatif du pays..." %>	
          <%= f.text_field :nationality,
           class:"placeholder:italic placeholder:text-slate-400
           outline-none border my-2 rounded-md py-2 w-full 
           focus:outline-none focus:ring focus:border-blue-200",
            placeholder:"Votre Nationalité..." %>	
        <div class="flex w-full">
          <div class="mr-4">
            <p class="font-semibold">Salarié? :</p>
          </div>
          <%= f.radio_button :employer, 'Non', checked: true%> <span class="mx-2">Non</span>
          <%= f.radio_button :employer, 'Oui' %> <span class="mx-2">Oui</span>
          <%= f.radio_button :employer, 'Entrepreneur' %> <span class="mx-2">Entrepreneur</span>
        </div>
          <%= f.text_field :profession, class:"flex border py-2  rounded-md w-full 
          placeholder:mx-4 outline-none", placeholder:"Votre Profession..." %>	
        
        <div class="flex w-full">
          <div class="mr-4">
            <p class="font-semibold">Matrimoniale? :</p>
          </div>
          <%= f.radio_button :matrimonial, 'Mademoiselle', checked: true , class:"ml-2"%> <span class="mr-2">Mlle</span>
          <%= f.radio_button :matrimonial, 'Madame', class:"ml-2" %> <span class="mr-2">Mme</span>
          <%= f.radio_button :matrimonial, 'Monsieur' %> <span class="">M.</span>
        </div>
        
        <div class="flex w-full">
          <div class="mr-4">
            <p class="font-semibold">Vous êtes? :</p>
          </div>
          <%= f.radio_button :gender, 'Femme' , checked: true, class:"ml-2"%> <span class:"mr-2">Femme</span>
          <%= f.radio_button :gender, 'Homme', class:"ml-2"%> <span class="">Homme</span>
        </div>
        <div class="w-full my-2">
          <div class="">
            <p class="font-semibold sm:text-sm">Comment avez vous connu Action<sup class="">+</sup> ? : <br></p>
          </div>
          <%= f.radio_button :source, 'Ami' , checked: true , class:"ml-2" %> <span class="mr-2">Ami(e)</span>
          <%= f.radio_button :source, 'Réseau_Sociaux' %> <span class="mr-2">Réseau Sociaux</span>
          <%= f.radio_button :source, 'Autres' %> <span class="mx-2">Autres</span>
          
        </div>


        <div class="flex items-center  py-2 ">
          <%= f.check_box :terms, value:"oui", class:" mr-4", checked:true %>
          <p class="text-sm">
          
            Oui, j'adhère à <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal-1" class="font-semibold underline">
            la charte des valeurs</a>, <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal-2" class="font-semibold underline"> aux statuts</a> et  <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal-3" class="font-semibold underline"> aux règles de fonctionnement d'Action</a><sup class="">+</sup>, ainsi qu'aux
            <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal-4" class="font-semibold underline">conditions générales d'utilisation </a> <span class="no-underline ">et à la politique
            de</span>   <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal-5" class="font-semibold underline ml-1"> protection des données </a> de la plateforme.
          </p>
        </div>
        <div>
          <%= f.submit "Oui J'Adhère", class:"uppercase block w-full bg-green-600 mt-2 py-2 pb-2 rounded-2xl text-white font-semibold mb-2" %>
        </div>
        </div>
    <% end %>
	</div>
</div>


<!-- Modal Privacy-->
<div class="modal fade" id="exampleModal-1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title font-semibold" id="exampleModalLabel">Résumé: Chartes des valeurs</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Le Résumé s'affichera ici
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-gray-100 text-black " data-bs-dismiss="modal">Fermer</button>
        
      </div>
    </div>
  </div>
</div>
<!-- Modal Charte -->
<div class="modal fade" id="exampleModal-2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title font-semibold" id="exampleModalLabel">Résumé des Status<sup class="">+</sup></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
       Le Résumé s'affichera ici
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-gray-100 text-black " data-bs-dismiss="modal">Fermer</button>
        
      </div>
    </div>
  </div>
</div>
<!-- Modal règles de fonctionnement d'Action-->
<div class="modal fade" id="exampleModal-3" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title font-semibold" id="exampleModalLabel">Résumé: Règles de fonctionnement d'Action<sup class="">+</sup></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      Le Résumé s'affichera ici
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-gray-100 text-black " data-bs-dismiss="modal">Fermer</button>
        
      </div>
    </div>
  </div>
</div>
<!-- Modal CGU-->
<div class="modal fade" id="exampleModal-4" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title font-semibold" id="exampleModalLabel">Résumé: Les conditions générale d'utilisation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
       Le Résumé s'affichera ici
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-gray-100 text-black " data-bs-dismiss="modal">Fermer</button>
        
      </div>
    </div>
  </div>
</div>
<!-- Modal CGU-->
<div class="modal fade" id="exampleModal-5" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title font-semibold" id="exampleModalLabel">Résumé: protection des données</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Le Résumé s'affichera ici
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary bg-gray-100 text-black " data-bs-dismiss="modal">Fermer</button>
        
      </div>
    </div>
  </div>
</div>

app/views/bememberships/edit.html.erb
<%= render "form", bemembership: @bemembership %>

app/views/bememberships/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bememberships</h1>

<div id="bememberships">
  <% @bememberships.each do |bemembership| %>
    <%= render bemembership %>
    <p>
      <%= link_to "Show this bemembership", bemembership %>
    </p>
  <% end %>
</div>

<%= link_to "New bemembership", adhesion_path %>

app/views/bememberships/new.html.erb
<%= render "form", bemembership: @bemembership %>

app/views/bememberships/page_good.html.erb
<p style="color: green"><%= notice %></p>

<!-- component -->
<div class="container py-4 px-8 bg-white border rounded-lg my-20">
  <div class="flex justify-center md:justify-end -mt-16">
    <%= image_tag "logo/logo-action.png", class:"w-20 h-20 object-cover rounded-full border-2 border-indigo-500" %>
  </div>
  <div>
    <h2 class="text-gray-800 text-3xl font-semibold">Bienvenue Parmis nous</h2>
    <p class="mt-2 text-gray-600">Votre Adhesion est bien récu!  </p>
    <p class="mt-2 text-gray-600">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit ass  </p>
  </div>
  <div class="flex justify-end mt-4">
    
    <%= link_to 'Découvrez Nos projets', "action-projet" , class:"text-xl font-medium text-indigo-500" %>
  </div>
</div>

app/views/bememberships/show-b.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bemembership %>

<div>
  <%= link_to "Edit this bemembership", edit_bemembership_path(@bemembership) %> |
  <%= link_to "Back to bememberships", bememberships_path %>

  <%= button_to "Destroy this bemembership", @bemembership, method: :delete %>
</div>