config/routes.rb
Rails.application.routes.draw do
  root to:'welcome#index'
  
  
  get "adhesion", to:'bememberships#new'
  get 'good', to:"bememberships#page_good"
  
  
  #Legal
  get "charte", to:"legals#show"
  get "vie-privée", to:"privates#show"
  
  
  get "agir", to:'agir#index'
  
  get "action-projet", to:'action_page#index'
  #get "dons", to:'donner#index'
  #### Accounted #####
  get "connecting", to:'accounted#signInMember'
  get "adhesion-partner", to:'accounted#signUpMember'
  get "admin-accounted", to:'accounted#signUpAdmin'
  
  #DASHBOARD
  get "dashboard", to:'dashboard#index'
  get "parametres", to:'dashboard#home'
  get "agisons-ensemble", to:"involved#index"
  
  # MEMBERSHIP
  get "adherer", to:'membership#index'
  get "members-list", to:"membership#memberslist"
  get "beaction-v", to:"membership#beaction"


  # CAMPAGNES
  get "new-campagne", to:"campagnes#new"
  get "campagnes", to:"campagnes#index"
  get "edit-campagnes", to:"campagnes#edit"

  #BENEVOLS
  get "New-benevol", to:"benevols#new"
  get "benevols", to:"benevols#index"

  #PROJETS
  get "new-projet", to:"projets#new"
  get "projets-list", to:"projets#index"
  #put "edit-projet", to:"projets#edit"
  


  devise_scope :user do
    get 'profile/edit'    => 'devise/registrations#edit',   :as => :edit_user_registration
    get 'profile/cancel'  => 'devise/registrations#cancel', :as => :cancel_user_registration
    
  end
  

  resources :bememberships
  resources :privates
  resources :legals
  resources :articles
  resources :blogs
  resources :benevols, except: %i[new, index]
  resources :projets
  resources :campagnes
  
  devise_for  :users,
    :path => '',
    :path_names =>
      { :sign_in => 'beaction',
        :sign_out => 'logout',
        :sign_up =>   '', 
          :registration => 'signup-admin',
          :edit => 'edit'
      }
  
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  has_one_attached :heroImg
  

  STATUS= ["Encours", "Approbation", "Public", "La lune", "Archive"]
  validates :title, :content, :write_date, :slug, presence: true
  validates :title, :content, length: { minimum:5}


   ################## SLUG ###############
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
   title_changed?
  end
end

app/models/bemembership.rb
class Bemembership < ApplicationRecord
    validates :first_name, :last_name, :email,
              :country, :contact, :gender, :terms, :citytown,
                :employer, :profession, :matrimonial,
                 :nationality, presence: true

    
    validates :first_name, :last_name, :source,
                :employer, :profession, :matrimonial,
                :nationality,
              format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ },
              length: { maximum: 30,
              message: "%{value} verifier votre nom complet"}
    validates :contact,
             #format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ },
              length: { maximum: 16,
              message: "%{value} verifier votre Numéro"}
end

app/models/benevol.rb
class Benevol < ApplicationRecord
     has_one_attached :img
    STATUS= ["La Lune", "Status 2", "Status 3"]
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user

   ################## SLUG ###############
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
   title_changed?
  end

  
end

app/models/campagne.rb
class Campagne < ApplicationRecord
  belongs_to :user
  has_one_attached :heroImg
  has_rich_text :content
  
  Campagne.all.with_rich_text_content # Preload the body without attachments.
  Campagne.all.with_rich_text_content_and_embeds # Preload both body and attachments.


  STATUS= ["Encours", "Approver", "La lune", "Archive" ]
  validates :title, :content, :start_date, :amount, presence: true
  #validates_comparison_of :start_date, greater_than: -> { Date.today }
  validates :title, :content, length: { minimum:5}


  ################## SLUG ###############
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
   title_changed?
  end
end

app/models/legal.rb
class Legal < ApplicationRecord
  belongs_to :user
end

app/models/membership.rb
class Membership < ApplicationRecord
    
end

app/models/private.rb
class Private < ApplicationRecord
  belongs_to :user
end

app/models/projet.rb
class Projet < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  #Projet.all.with_rich_text_content # Preload the body without attachments.
  #Projet.all.with_rich_text_content_and_embeds # Preload both body and attachments.
  has_one_attached :heroImg

  STATUS= ["Encours", "Approver", "La lune", "Archive"]
  validates :title, :content, :start_date, :amount, presence: true
  validates :title, :content, length: { minimum:5}


  ################## SLUG ###############
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
   title_changed?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :posts
  has_many :abouts
  has_many :projets
  has_many :campagnes
  has_many :blogs
  has_many :articles
  has_many :legals
  has_many :privates
  has_one_attached :avatar

  def full_name
    self.full_name = "#{self.first_name} #{self.last_name}" 
  end  
   
  def slug
    self.slug = "#{self.full_name}" 
  end

  validates :first_name, :last_name, :full_name, :email, :password,
              :country, :full_contact, presence: true
    
   validates :full_name,presence: true,
              format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/ },
              length: { minimum:5, maximum: 30,
              message: "%{value} verifier votre nom complet"}

                

   ################## SLUG ###############
  extend FriendlyId
  friendly_id :full_name, use: :slugged
  
  def should_generate_new_friendly_id?
    full_name_changed?
  end 
 
  
  ################## BEFORE SAVE  #########
  before_save do
    #self.country            = country.strip.squeeze(" ")
    self.full_contact            = full_contact .strip.squeeze(" ")
    self.first_name         = first_name.strip.squeeze(" ").downcase.capitalize
    self.last_name          = last_name.strip.squeeze(" ").downcase.capitalize
  end
end

app/controllers/accounted_controller.rb
class AccountedController < ApplicationController
  def signInMember
  end

  def signUpAdmin
  end

  def signMember
  end
end

app/helpers/accounted_helper.rb
module AccountedHelper
end

app/helpers/agir_helper.rb
module AgirHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/benevols_helper.rb
module BenevolsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/involved_helper.rb
module InvolvedHelper
end

app/helpers/legals_helper.rb
module LegalsHelper
end

app/helpers/privates_helper.rb
module PrivatesHelper
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounted/signInMember.html.erb
<!-- Onglet Title -->
<% @title="Connectez-vous" %>

<!-- component -->
<section class="flex flex-col md:flex-row h-screen items-center">

  <div class="bg-indigo-600 hidden lg:block w-full md:w-1/2 xl:w-2/3 h-screen">
    <img src="https://source.unsplash.com/random" alt="" class="w-full h-full object-cover">
  </div>

  <div class="bg-white w-full md:max-w-md lg:max-w-full md:mx-0 md:w-1/2 xl:w-1/3 h-screen px-6 lg:px-16 xl:px-12
        flex items-center justify-center">

    <div class="w-full h-100">


      <h1 class="text-xl md:text-2xl font-bold leading-tight mt-12">Connectez-vous a votre compte</h1>

     
      <%= form_for(resource, as: resource_name, class:"mt-6", url: session_path(resource_name)) do |f| %>
        <!-- Notice error-->
        <%= render_notification %>
        <div>
          <label class="block text-gray-700">Addresse Email</label>
          <input type="email" name="" id="" placeholder="Entrez Addresse Email " class="w-full px-4 py-3 rounded-lg bg-gray-200 mt-2 border focus:border-blue-500 focus:bg-white focus:outline-none" autofocus autocomplete required>
        </div>

        <div class="mt-4">
          <label class="block text-gray-700">Mot de passe</label>
          <input type="password" name="" id="" placeholder="*************" minlength="6"
           class="w-full px-4 py-3 rounded-lg bg-gray-200 mt-2 border focus:border-blue-500
                focus:bg-white focus:outline-none" required>
        </div>

        <div class="text-right mt-2">
          <a href="#" class="text-sm font-semibold text-gray-700 hover:text-blue-700 focus:text-blue-700">
          Entrez un mot de passe superieur à 9 caractères</a>
        </div>

        <button type="submit" class="w-full block bg-indigo-500 hover:bg-indigo-400 focus:bg-indigo-400 text-white font-semibold rounded-lg
              px-4 py-3 mt-6">Se Connecter</button>
      <% end %>

      <hr class="my-6 border-gray-300 w-full">

       

      <p class="mt-8">Bésoin d'un compte? <%= link_to "Créer un compte", new_user_registration_path, class:"text-blue-500 hover:text-blue-700 font-semibold"%></p>


    </div>
  </div>

</section>

app/views/accounted/signUpAdmin.html.erb
<h1>Accounted#signUpAdmin</h1>
<p>Find me in app/views/accounted/signUpAdmin.html.erb</p>

app/views/accounted/signUpMember.html.erb
<!-- Onglet Title -->
<% @title="Adhesion" %>


<!-- component -->
<div class="h-screen md:flex">
	<div class="relative overflow-hidden md:flex w-1/3 bg-gradient-to-tr from-green-400 to-blue-600 i justify-around items-center hidden">
		<div class="container">

			<h1 class="text-white font-bold text-4xl font-sans"> 
        <span class="before:block before:absolute before:-inset-1 before:-skew-y-3 before:bg-pink-500 relative inline-block">
        <span class="relative text-white">Adhésion</span>
      </span>
      <br> à l'organisation humanitaire Action<sup>+</sup>
      </h1>
			<p class="text-black mt-1">Vous voulez contribuer à sauver des vies ? <br> Rejoignez la communauté Action<sup>+</sup> !
<br> <span class="font-semibold underline"> C'est facile, gratuit et 1 minute suffira.</span></p>
			
    <button type="submit" class="block uppercase  bg-white text-indigo-600
      mt-4 py-2 rounded-2xl font-bold m-2" onclick="openModal('modal')" >
      Ensemble pour plus d'Action
      <sup>+</sup>
    </button>
		</div>
		<div class="absolute -bottom-32 -left-40 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
		<div class="absolute -bottom-40 -left-20 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
		<div class="absolute -top-40 -right-0 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
		<div class="absolute -top-20 -right-20 w-80 h-80 border-4 rounded-full border-opacity-30 border-t-8"></div>
	</div>
	<div class="flex md:w-2/3 justify-center  items-center bg-white">
	
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>

      <%= render_notification %>

		<h1 class="text-gray-800 font-bold text-2xl mb-2">Vous et Action<sup>+</sup> Agisons Ensemble pour sauver des vies</h1>
		<p class="text-sm font-normal text-gray-600 mb-2">Devenez Membre Adherent d'Action<sup>+</sup></p>

			<div class="flex items-center mt-8 mb-2">
          <%= f.text_field :first_name, class:"placeholder:italic placeholder:text-slate-400 outline-none border rounded-md py-2 w-full", placeholder:"Nom ..." %>
          <%= f.text_field :last_name, class:"placeholder:italic placeholder:text-slate-400 outline-none border ml-2 rounded-md py-2 w-full", placeholder:"Prénom..." %>
      </div>
	
        <%= f.email_field :email, placeholder:"Addresse Email ...", class:"placeholder:italic placeholder:text-slate-400 flex border py-2 rounded-md w-full my-2" %>			
      
      <div class="flex w-full py-2 mb-2">
      <%#= f.country_select  :country, collection: countries_alpha3_options, format: :with_data_attrs, class:"pl-2 outline-none border rounded-md", placeholder:"pays code..." %>
          <%#= f.country_select :country, priority_countries: ["CI", "FR", "CA", "US"],
           prompt: "Votre pays", format: :with_data_attrs,
          class:"placeholder:italic placeholder:text-slate-400 flex border py-2 rounded-md w-full" %>
      </div>
    
      
      <div class="flex w-full py-2 mb-2">
        <%= f.text_field :country, placeholder:"Code pays ...", class:"flex border py-2 ml-2 rounded-md w-full placeholder:mx-4" %>	
        <%= f.text_field :contact, placeholder:"N° telephone ...", class:"flex border py-2 ml-2 rounded-md w-full placeholder:mx-4" %>	
      </div>
      
        <%= f.password_field :password, class:"flex border py-2 rounded-md w-full", placeholder:"Mot de passe ..." %>				
      <%= f.hidden_field :category, value:"Adherent" %>
      <div class="flex items-center  py-2 ">
      <%= f.check_box :terms, value:"oui", class:" mr-4", checked:true %>
      <p class="text-sm">
        Oui, j'adhère à <%= link_to root_path, class:"font-semibold" do %> la charte des valeurs, aux statuts et 
        aux règles <br />de fonctionnement  de ACTION+, <% end %> <br />ainsi qu'aux
        <%= link_to "conditions générales d'utilisation", root_path %> de la plateforme et à la politique <br />
        de <%= link_to 'protection des données', root_path ,class:"font-semibold" %> à caractère personnel de la plateforme.
       </p>
      </div>
      
      <%= f.submit "Créer,Votre Compte", class:"block w-full bg-green-600 mt-2 py-2 pb-2 rounded-2xl text-white font-semibold mb-2" %>
		<% end %>
	</div>
</div>


        <!-- Modal apprendre plus -->


<div id="modal" class="fixed hidden z-50 inset-0 bg-gray-900 bg-opacity-60 overflow-y-auto h-full w-full px-4">
    <div class="relative top-40 mx-auto shadow-lg rounded-md bg-white max-w-md">

        <!-- Modal header -->
        <div class="flex justify-between items-center bg-green-500 text-white text-md rounded-t-md px-4 py-2">
            <h3 class="uppercase">charte des valeurs</h3>
            <button onclick="closeModal()">x</button>
        </div>

        <!-- Modal body -->
        <div class="max-h-48 overflow-y-scroll p-4">
            <p>Scrollable modal body</p>
            <p>Scrollable modal body</p>
            <p>Scrollable modal body</p>
            <p>Scrollable modal body</p>
            <p>Scrollable modal body</p>
            <p>Scrollable modal body</p>
            <p>Scrollable modal body</p>
            <p>Scrollable modal body</p>
            <p>Scrollable modal body</p>
            <p>Scrollable modal body</p>
        </div>

        <!-- Modal footer -->
        <div class="px-4 py-2 border-t border-t-gray-500 flex justify-end items-center space-x-4">
            <button class="bg-blue-500 text-black border-1 px-4 py-2 rounded-md hover:bg-blue-700 transition" onclick="closeModal()">Fermer</button>
        </div>
    </div>
</div>